<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class HostingPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('hosting_plans')->insert([
            [ // 1
                'plan_type_id' => 1,
                'name' => 'Web – FREE',
                'ssl' => 1,
                'ram' => 0.5,
                'cpu' => 0.5,
                'hosting_app_storage' => 10,
                'hosting_db_storage' => 10,
                'mailbox' => 0,
                'mailbox_size' => null,
                'backup' => 0,
                'duration' => 6,
                'sort' => 1,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 2
                'plan_type_id' => 1,
                'name' => 'Web – Basic',
                'ssl' => 1,
                'ram' => 1,
                'cpu' => 1,
                'hosting_app_storage' => 10,
                'hosting_db_storage' => 10,
                'mailbox' => 0,
                'mailbox_size' => null,
                'backup' => 0,
                'duration' => 12,
                'sort' => 2,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 3
                'plan_type_id' => 1,
                'name' => 'Web – PRO',
                'ssl' => 1,
                'ram' => 1.5,
                'cpu' => 1.5,
                'hosting_app_storage' => 15,
                'hosting_db_storage' => 15,
                'mailbox' => 1,
                'mailbox_size' => 5,
                'backup' => 0,
                'duration' => 12,
                'sort' => 3,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 4
                'plan_type_id' => 1,
                'name' => 'Web – VIP',
                'ssl' => 1,
                'ram' => 2,
                'cpu' => 2,
                'hosting_app_storage' => 20,
                'hosting_db_storage' => 20,
                'mailbox' => 1,
                'mailbox_size' => 10,
                'backup' => 1,
                'duration' => 12,
                'sort' => 4,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 5
                'plan_type_id' => 2,
                'name' => 'Business – FREE',
                'ssl' => 1,
                'ram' => 1,
                'cpu' => 1,
                'hosting_app_storage' => 10,
                'hosting_db_storage' => 10,
                'mailbox' => 0,
                'mailbox_size' => null,
                'backup' => 0,
                'duration' => 1,
                'sort' => 5,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 6
                'plan_type_id' => 2,
                'name' => 'Business – Basic',
                'ssl' => 1,
                'ram' => 2,
                'cpu' => 1,
                'hosting_app_storage' => 10,
                'hosting_db_storage' => 10,
                'mailbox' => 0,
                'mailbox_size' => null,
                'backup' => 0,
                'duration' => 12,
                'sort' => 6,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 7
                'plan_type_id' => 2,
                'name' => 'Business – PRO',
                'ssl' => 1,
                'ram' => 3,
                'cpu' => 1.5,
                'hosting_app_storage' => 20,
                'hosting_db_storage' => 20,
                'mailbox' => 1,
                'mailbox_size' => 30,
                'backup' => 1,
                'duration' => 12,
                'sort' => 7,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ // 8
                'plan_type_id' => 2,
                'name' => 'Business – VIP',
                'ssl' => 1,
                'ram' => 4,
                'cpu' => 2,
                'hosting_app_storage' => 30,
                'hosting_db_storage' => 30,
                'mailbox' => 1,
                'mailbox_size' => 40,
                'backup' => 1,
                'duration' => 12,
                'sort' => 8,
                'active' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
