<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class SystemDomainSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('system_domains')->insert([
            [
                'remote_domain_id' => 25940759,
                'customer_id' => 10890501,
                'domain_type_id' => 1,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'magicak-sg.com',
                'domain_auth_key' => '58ae1631cacedN_}',
                'ip' => '195.133.139.169',
                'active' => 1,
                'Registration_date' => '2022-07-03',
                'Expiration_date' => '2024-07-03',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 2989,
                'customer_id' => 283,
                'domain_type_id' => 2,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'premium.magicak-sg.net',
                'domain_auth_key' => '',
                'ip' => '1.2.3.1',
                'active' => 1,
                'Registration_date' => '2022-05-22',
                'Expiration_date' => '2023-05-22',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 1327,
                'customer_id' => 283,
                'domain_type_id' => 1,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'magicak-auz.com',
                'domain_auth_key' => '2da72cfa09bdaU(_',
                'ip' => '1.2.3.22',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 2991,
                'customer_id' => 283,
                'domain_type_id' => 2,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'premium.magicak-auz.com',
                'domain_auth_key' => '',
                'ip' => '1.2.3.2',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 1249,
                'customer_id' => 283,
                'domain_type_id' => 1,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'magicak-vn.com',
                'domain_auth_key' => 'e726cbaba9f72T=^',
                'ip' => '1.2.3.33',
                'active' => 1,
                'Registration_date' => '2022-05-22',
                'Expiration_date' => '2023-05-22',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 2993,
                'customer_id' => 283,
                'domain_type_id' => 2,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'premium.magicak-vn.com',
                'domain_auth_key' => '',
                'ip' => '1.2.3.3',
                'active' => 1,
                'Registration_date' => '2022-05-22',
                'Expiration_date' => '2023-05-22',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 1323,
                'customer_id' => 283,
                'domain_type_id' => 1,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'magicak-jp.com',
                'domain_auth_key' => 'e5faf61ba0f1fG#{',
                'ip' => '1.2.3.44',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 2995,
                'customer_id' => 283,
                'domain_type_id' => 2,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'premium.magicak-jp.com',
                'domain_auth_key' => '',
                'ip' => '1.2.3.4',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 1325,
                'customer_id' => 283,
                'domain_type_id' => 1,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'magicak-cn.com',
                'domain_auth_key' => '580aec748adaeH)|',
                'ip' => '1.2.3.55',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'remote_domain_id' => 2997,
                'customer_id' => 283,
                'domain_type_id' => 2,
                'Domain_Register_from' => 'Vodien',
                'Domain_name' => 'premium.magicak-cn.com',
                'domain_auth_key' => '',
                'ip' => '1.2.3.5',
                'active' => 1,
                'Registration_date' => '2022-06-02',
                'Expiration_date' => '2023-06-02',
                'created_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
