stages:
  - build-and-deploy-dev
  - install-dependencies-staging
  - build-k8s-cluster-staging
  - deploy-k8s-cluster-staging

build-and-deploy-dev:
  stage: build-and-deploy-dev
  tags:
    - "k8s-dev"
  only:
    - develop
  script:
    - /home/dev/demo/magicak/clear-cache.sh
    # - POD_NAME=$(kubectl get pod -n magicak-web | grep php- | awk '{ print $1; }')
    # - kubectl exec $POD_NAME -n magicak-web -- sh -c "git pull origin develop && php artisan view:clear && php artisan cache:clear && php artisan route:clear && php artisan config:clear && php artisan clear-compiled && php artisan optimize && rm -Rf ./bootstrap/cache/*.php"

install-dependencies-staging:
  stage: "install-dependencies-staging"
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor
  tags:
    - "k8s-dev"
  only:
    - staging
  script:
    - cat $FILE_ENV_STAGING > .env
    - composer install --no-interaction --no-dev --no-progress --no-suggest --optimize-autoloader

build-k8s-cluster-staging:
  stage: build-k8s-cluster-staging
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor
  tags:
    - "k8s-dev"
  only:
    - staging
  script:
    - cat $FILE_ENV_STAGING > .env
    - sudo php artisan view:clear && sudo php artisan cache:clear && sudo php artisan route:clear && sudo php artisan config:clear && sudo php artisan clear-compiled && sudo php artisan optimize
    - sudo rm -Rf ./bootstrap/cache/*.php
    - sudo ln -s /var/www/html/storage/app/public ./public/storage
    - sudo docker build -f Dockerfile.php -t kaitoryouga/laravel-php:${CI_COMMIT_SHORT_SHA} .
    - sudo docker push kaitoryouga/laravel-php:${CI_COMMIT_SHORT_SHA}

deploy-k8s-cluster-staging:
  stage: deploy-k8s-cluster-staging
  tags:
    - "k8s-dev"
  only:
    - staging
  script:
    - POD_NAME=$(kubectl get pod -n magicak-web | grep php- | awk '{ print $1; }')
    - rm -rf /tmp/public.tar > /dev/null 2>&1
    - kubectl exec $POD_NAME -- tar cvf /tmp/public.tar -C /app/html/storage/app/public .
    - kubectl cp $POD_NAME:/tmp/public.tar /tmp/public.tar
    - tar xvf /tmp/public.tar -C /tmp/data-magicak
    - kubectl set image deployments/php php=kaitoryouga/laravel-php:${CI_COMMIT_SHORT_SHA}
    - chmod +x sync-data.sh
    - ./sync-data.sh
